version: '3'
services:
  node:
    container_name: node-messages
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
    links:
      - mongo
      - redis
  redis:
    container_name: node-messages-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data/db
  mongo:
    container_name: node-messages-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: